<h2><center>Assignment 6</center></h2>
<h3><center>Programming for Data Science 2026</center></h3>
<b><center>Deadline: 14:00, April 16, 2026</center></b>

- The exercise will be marked as **passed** if you get **at least 10/16** points.

- Exercises must be handed in via **ILIAS** (Homework assignments). Submit your work as a **compressed (.zip)** file containing **one** `.py` **or** `.ipynb` file with **all exercises**.

- The name of **both** the `.zip` file and the `.py`/`.ipynb` file must be the *SurnameName* of the **two group members**, separated by an underscore.  
  Example: Tim Tabellen and Lara Lambda → `TabellenTim_LambdaLara.zip`  
  (The `.py`/`.ipynb` file must have the same name.)

- Use **comments** to explain your code and demonstrate that you understand the solutions and can discuss them.

- You are not expected to collaborate outside your group. Submitting other groups’ code as your own will result in **0 points**.

- For general questions about the lecture content, assignments, or the exam, please use the **ILIAS forum**.

- For individual questions about lecture content and the exam, contact: *roland.widmer@students.unibe.ch*  

- For individual questions about the exercises or grading, contact: *julien.brunner@students.unibe.ch* or *aline.steiner@students.unibe.ch*

#### Exercise 1: MultiIndex *(5 points)*

In this exercise you will create and manipulate a multi-index dataframe.

In [1]:
import pandas as pd

stores = [
    ('Länggasse', 'Mittelstrasse'),
    ('Länggasse', 'Falkenplatz'),
    ('Länggasse', 'Neufeld'),
    ('Bümpliz', 'Höhe'),
    ('Breitenrain',  'Breitenrainplatz'),
    ('Breitenrain',  'Kaserne'),
] # schema: region, name of the store

data = [
    [120, 135, 150, 160, 130, 140, 155, 170],
    [100, 110, 120, 130, 105, 115, 125, 140],
    [ 90,  95, 100, 105,  92,  98, 100, 105],
    [0, 0, 0, 255, 250, 260, 253, 230],
    [200, 210, 220, 230, 205, 215, 225, 240],
    [180, 190, 200, 210, 182, 192, 202, 215],
]

Our fictional vintage clothing company has six stores in Bern. One of the stores opened recently. For the years 2024 and 2025, the quarterly sales are stored in the matrix `data` (each row represents one store and each column represents one quarter). Note that the sales of the Höhe store are 0 for 2024 Q1–Q3 because the store opened in 2024 Q4.

1. Create a MultiIndex using `stores` and `pd.MultiIndex.from_tuples`. Name the index levels `region` and `store`.

In [2]:
stores_index = pd.MultiIndex.from_tuples(stores, names=["region", "store"])

2. Create the columns of our dataframe by calculating all possible combinations of years and quarters. Use the appropriate method offered by pandas.

In [3]:
years = [2024, 2025]
quarters = ['Q1', 'Q2', 'Q3', 'Q4']

sales_index = pd.MultiIndex.from_product([years, quarters], names=['Year', 'Quarter'])

# df_columns = pd.DataFrame(columns=sales_index)

3. Create a pandas DataFrame `sales_df` using `data` and the index and columns created above.

In [4]:
sales_df = pd.DataFrame(data=data, columns=sales_index, index=stores_index)

sales_df

Year                         2024                2025
Quarter                        Q1   Q2   Q3   Q4   Q1   Q2   Q3   Q4
region      store
Länggasse   Mittelstrasse     120  135  150  160  130  140  155  170
            Falkenplatz       100  110  120  130  105  115  125  140
            Neufeld            90   95  100  105   92   98  100  105
Bümpliz     Höhe                0    0    0  255  250  260  253  230
Breitenrain Breitenrainplatz  200  210  220  230  205  215  225  240
            Kaserne           180  190  200  210  182  192  202  215

4. The management would like to discuss the future of the Neufeld store which performs the worst among the stores in Länggasse. Print the sales of all stores in Länggasse in 2025 twice: once using `loc` and once using `xs`.

In [5]:
print(sales_df.loc["Länggasse"])
print("\n ------------------------------ \n")
print(sales_df.xs("Länggasse"))

Year          2024                2025
Quarter         Q1   Q2   Q3   Q4   Q1   Q2   Q3   Q4
store
Mittelstrasse  120  135  150  160  130  140  155  170
Falkenplatz    100  110  120  130  105  115  125  140
Neufeld         90   95  100  105   92   98  100  105

 ------------------------------

Year          2024                2025
Quarter         Q1   Q2   Q3   Q4   Q1   Q2   Q3   Q4
store
Mittelstrasse  120  135  150  160  130  140  155  170
Falkenplatz    100  110  120  130  105  115  125  140
Neufeld         90   95  100  105   92   98  100  105

5. Next, we are interested in the average quarterly sales in 2024 and want to compare them to the average quarterly sales in 2025.

- The 0 values for the Höhe store (which only opened in 2024 Q4) bias the quarterly average. Treat the 0 values for the Höhe store in 2024 Q1–Q3 as missing values when computing the 2024 average for that store.
- For every store, calculate the difference between quarterly average sales of 2024 and 2025.

Hint: Replacing the zeros with missing values might be helpful.

In [6]:
sales_df[sales_df == 0] = pd.NA

sales_df.loc[:, 2025].mean() - sales_df.loc[:, 2024].mean()

Quarter
Q1    22.666667
Q2    22.000000
Q3    18.666667
Q4     1.666667
dtype: float64

#### Exercise 2: Merging DataFrames *(3 points)*

We start by defining three DataFrames:

In [7]:
# Series
series_df = pd.DataFrame({
    'series_id': [1, 2, 3],
    'title': ['Stranger Things', 'The Office', 'Breaking Bad'],
    'genre': ['Sci-Fi', 'Comedy', 'Drama']
})

# Episodes
episodes_df = pd.DataFrame({
    'episode_id': [101, 102, 103, 201, 202, 301],
    'series_id': [1, 1, 1, 2, 2, 3],
    'season': [1, 1, 1, 1, 1, 1],
    'episode_number': [1, 2, 3, 1, 2, 1],
    'title': [
        'Chapter One', 'Chapter Two', 'Chapter Three',
        'Pilot', 'Diversity Day',
        'Pilot'
    ]
})

# Actors
actors_df = pd.DataFrame({
    'episode_id': [101, 101, 102, 103, 201, 202, 999],
    'actor': [
        'Millie Bobby Brown', 'Finn Wolfhard',
        'Millie Bobby Brown', 'Noah Schnapp',
        'Steve Carell', 'John Krasinski',
        'Unknown Actor'
    ]
})

1. Merge `episodes_df` with `series_df` to attach the series title and genre to each episode. Store the result as `episodes_full_df` with additional columns `series_title` and `genre`.

In [8]:
series_df = series_df.rename(columns={'title': 'series_title'})
episodes_full_df = episodes_df.merge(series_df, on="series_id")
episodes_full_df

,episode_id,series_id,season,episode_number,title,series_title,genre
0,101,1,1,1,Chapter One,Stranger Things,Sci-Fi
1,102,1,1,2,Chapter Two,Stranger Things,Sci-Fi
2,103,1,1,3,Chapter Three,Stranger Things,Sci-Fi
3,201,2,1,1,Pilot,The Office,Comedy
4,202,2,1,2,Diversity Day,The Office,Comedy
5,301,3,1,1,Pilot,Breaking Bad,Drama

2. Merge `episodes_df` with `actors_df` and store the result in `episode_actors_df`. Explain the difference between `how="inner"` and `how="left"` in this example, especially which rows are kept or discarded in each case.

In [9]:
#print(pd.merge(episodes_df, actors_df, how="inner"))
#print(pd.merge(episodes_df, actors_df, how="left"))

episodes_actors_df = pd.merge(episodes_df, actors_df, how="left")
episodes_actors_df

,episode_id,series_id,season,episode_number,title,actor
0,101,1,1,1,Chapter One,Millie Bobby Brown
1,101,1,1,1,Chapter One,Finn Wolfhard
2,102,1,1,2,Chapter Two,Millie Bobby Brown
3,103,1,1,3,Chapter Three,Noah Schnapp
4,201,2,1,1,Pilot,Steve Carell
5,202,2,1,2,Diversity Day,John Krasinski
6,301,3,1,1,Pilot,NaN

**Your answer**: Inner uses the intersection of keys from both dataframes so if they're not present in both it is discarded. Left instead use only keys from left frame ignoring the right. In the "inner" case the row 6 of episode_id 301 is discarded because it's not present in the actors dataframe, while it's kept for "left".

3. Create a dataframe `casting_df` with columns `episode_title`, `episode_number`, `season`, `series_title`, `actor` by combining the data from all three tables. Rename and reorder the columns where necessary. The final dataframe should contain all episodes, even if no actor is listed for them. Actor records with invalid episode_id values should be excluded.

In [10]:
series_renamed = series_df.rename(columns={'title': 'series_title'})
episodes_renamed = episodes_df.rename(columns={'title': 'episode_title'})

temp_df = episodes_renamed.merge(series_renamed, on='series_id')

casting_df = temp_df.merge(actors_df, on='episode_id', how='left') # keep everything

casting_df = casting_df[[
    'episode_title', 
    'episode_number', 
    'season', 
    'series_title', 
    'actor'
]]

casting_df

   episode_title  episode_number  season     series_title               actor
0    Chapter One               1       1  Stranger Things  Millie Bobby Brown
1    Chapter One               1       1  Stranger Things       Finn Wolfhard
2    Chapter Two               2       1  Stranger Things  Millie Bobby Brown
3  Chapter Three               3       1  Stranger Things        Noah Schnapp
4          Pilot               1       1       The Office        Steve Carell
5  Diversity Day               2       1       The Office      John Krasinski
6          Pilot               1       1     Breaking Bad                 NaN

#### Exercise 3: Gas prices *(5 points)*

In this exercise, we look at fuel prices in the UK.

Source: [fuelcosts.co.uk](https://www.kaggle.com/datasets/jamesb7/fuel-prices-uk?resource=download)

1. Using the files `data/csv/price_history.csv` and `data/csv/stations.csv`, create a merged dataframe `gas_prices_df`.

In [18]:
history_df = pd.read_csv('../data/csv/price_history.csv')
stations_df = pd.read_csv('../data/csv/stations.csv')

# 'node_id' as the common key
gas_prices_df = pd.merge(history_df, stations_df, on="node_id")

2. For the gas station with the cheapest petrol (E10) and the gas station with the cheapest diesel (B7_STANDARD) recorded on 30 March 2026, print the name (`trading_name`, `brand_name`, `organisation_name`) and the address (`address_line_1`, `city`, `county`, `postcode`).

Hint: To keep only rows recorded on 2026-03-30, you may use:

```python
days = pd.to_datetime(["2026-03-30"], utc=True)

gas_prices_df["recorded_at"] = pd.to_datetime(gas_prices_df["recorded_at"]).dt.normalize() # convert the column recorded_at to datetime and remove hours

filtered_gas_prices_df = gas_prices_df[
    gas_prices_df["recorded_at"].dt.isin(days)
]
```

In [34]:
days = pd.to_datetime(["2026-03-30"], utc=True)

gas_prices_df["recorded_at"] = pd.to_datetime(gas_prices_df["recorded_at"], utc=True).dt.normalize()

filtered_df = gas_prices_df[gas_prices_df["recorded_at"].isin(days)]

info_cols = ["trading_name", "brand_name", "organisation_name",
             "address_line_1", "city", "county", "postcode"]

# Cheapest E10
cheapest_e10 = (
    filtered_df[filtered_df["fuel_type"] == "E10"]
    .nsmallest(1, "price_pence")
    [info_cols]
)
print("Cheapest E10:\n", cheapest_e10)

# Cheapest B7_STANDARD (diesel)
cheapest_b7 = (
    filtered_df[filtered_df["fuel_type"] == "B7_STANDARD"]
    .nsmallest(1, "price_pence")
    [info_cols]
)
print("\nCheapest B7_STANDARD:\n", cheapest_b7)

Cheapest E10:
                      trading_name brand_name organisation_name  \
9047  KINGSWESTON SERVICE STATION     Valero               NaN

       address_line_1          city   county  postcode
9047  KINGSWESTON AVE  SHIREHAMPTON  BRISTOL  BS11 0AH

Cheapest B7_STANDARD:
                                            trading_name brand_name  \
9468  ASDA TOTTENHAM WHITE HART LANE PETROL FILLING ...       Asda

     organisation_name                      address_line_1    city  \
9468               NaN  335-337 WHITE HART LANE, TOTTENHAM  LONDON

              county postcode
9468  GREATER LONDON  N17 7LY

3. Set a MultiIndex using node_id, fuel_type, and recorded_at as index levels. Get all recorded prices for fuel type `E10` on the three days 2026-02-27, 2026-03-15, and 2026-03-30 using `.loc` or `.xs` and print the average price for the three days.

In [36]:
import numpy as np

days = pd.to_datetime(["2026-02-27", "2026-03-15", "2026-03-30"], utc=True)

# set MultiIndex
gas_prices_df_indexed = gas_prices_df.set_index(["node_id", "fuel_type", "recorded_at"]).sort_index()



for day in days:
    e10_data = gas_prices_df_indexed.xs("E10", level="fuel_type")
    avg_price = e10_data.xs(day, level="recorded_at")["price_pence"].mean()
    print(f"Average E10 price on {day.date()}: {avg_price:.4f}")

Average E10 price on 2026-02-27: 137.7181
Average E10 price on 2026-03-15: 148.3175
Average E10 price on 2026-03-30: 152.6418

4. Compare the average price of E10 fuel on 2026-03-30 between motorway and non-motorway stations.

In [37]:
day_march30 = pd.to_datetime("2026-03-30", utc=True)

march30_e10 = gas_prices_df[
    (gas_prices_df["recorded_at"] == day_march30) &
    (gas_prices_df["fuel_type"] == "E10")
]

avg_by_motorway = march30_e10.groupby("is_motorway")["price_pence"].mean()
print("\nAverage E10 price by motorway status:\n", avg_by_motorway)

Average E10 price by motorway status:
 is_motorway
False    152.214775
True     169.643662
Name: price_pence, dtype: float64

5. Compare the average E10 price change over the last month for the following four brands: Esso, BP, Shell, and Sainsbury’s. Iterate through the four brands and calculate a subset dataframe containing only the rows of that brand. For every brand, calculate the difference of the mean E10 price on 2026-02-27 and on 2026-03-30. Print the price difference.

In [38]:
brands = ["Esso", "Bp", "Shell", "Sainsbury'S"]
day_1 = pd.to_datetime("2026-02-27", utc=True)
day_2 = pd.to_datetime("2026-03-30", utc=True)

for brand in brands:
    brand_df = gas_prices_df[
        (gas_prices_df["brand_name"] == brand) &
        (gas_prices_df["fuel_type"] == "E10")
    ]
    mean_day1 = brand_df[brand_df["recorded_at"] == day_1]["price_pence"].mean()
    mean_day2 = brand_df[brand_df["recorded_at"] == day_2]["price_pence"].mean()
    diff = mean_day2 - mean_day1
    print(f"{brand}: price change = {diff:.4f} pence")

Esso: price change = 20.5816 pence
Bp: price change = 20.6366 pence
Shell: price change = 16.7327 pence
Sainsbury'S: price change = 18.2248 pence

#### Exercise 4: Fitbit *(3 points)*

In this exercise, we work with a Fitbit data set.

Source: [https://www.kaggle.com/datasets/arashnic/fitbit](https://www.kaggle.com/datasets/arashnic/fitbit)

Unfortunately, some values are missing in the `TotalSteps` and `Calories` columns.

1. Read `data/csv/fitbit.csv` and store it in a pandas DataFrame `fitbit_df`. Print the number of missing values in the columns `Calories` and `TotalSteps`.

In [43]:
fitbit_df = pd.read_csv("../data/csv/fitbit.csv")

missing_calories = fitbit_df["Calories"].isna().sum()
missing_steps = fitbit_df["TotalSteps"].isna().sum()

print(f"Missing values in Calories:   {missing_calories}")
print(f"Missing values in TotalSteps: {missing_steps}")

Missing values in Calories:   43
Missing values in TotalSteps: 68

2. Let us assume that there is a direct linear relationship between calories and total steps:

    $n_{calories} = n_{steps} \cdot c, $
    
    $n_{steps} = n_{calories} \cdot s, $

    where $c$ denotes calories per step and $s=\frac{1}{c}$ steps per calorie.

    Estimate $c$ by calculating the average calories divided by the average total steps.

In [44]:
c = fitbit_df["Calories"].mean() / fitbit_df["TotalSteps"].mean()
s = 1 / c  # steps per calorie

print(f"Calories per step (c): {c:.6f}")
print(f"Steps per calorie  (s): {s:.6f}")

Calories per step (c): 0.293251
Steps per calorie  (s): 3.410045

3. Fill the missing values using our estimation technique. Can this approach fill all missing values? Explain the result.

In [ ]:
# If Calories is missing but TotalSteps is known: Calories = TotalSteps * c
fitbit_df["Calories"] = fitbit_df["Calories"].fillna(fitbit_df["TotalSteps"] * c)

# If TotalSteps is missing but Calories is known: TotalSteps = Calories * s
fitbit_df["TotalSteps"] = fitbit_df["TotalSteps"].fillna(fitbit_df["Calories"] * s)

# Check remaining missing values after imputation
still_missing_calories = fitbit_df["Calories"].isna().sum()
still_missing_steps    = fitbit_df["TotalSteps"].isna().sum()

print(f"Remaining missing Calories:   {still_missing_calories}")
print(f"Remaining missing TotalSteps: {still_missing_steps}")

Remaining missing Calories:   13
Remaining missing TotalSteps: 13

### Explanation:
This approach cannot fill all missing values. Rows where both Calories and TotalSteps are missing simultaneously cannot be imputed, because we need at least one value to estimate the other. In our dataset, 13 such rows exist and remain NaN after imputation.